steps:
- name: gcr.io/k8s-skaffold/pack
  entrypoint: pack
  args:
  - build
  - us-west1-docker.pkg.dev/sohansm-project/cloud-run-source-deploy/immerse-next
  - --builder
  - gcr.io/buildpacks/builder:latest

images:
- us-west1-docker.pkg.dev/sohansm-project/cloud-run-source-deploy/immerse-next
